@startuml ClientResourceServerAuthUML

title PKCE Flow with Resource Server and Keycloak

actor User as User
participant "Client Application" as Client
participant "Keycloak Server" as Keycloak
participant "Resource Server" as ResourceServer



User -> Client: Access Application
Client -> Client: Generate Code Verifier\nand Code Challenge
Client -> Keycloak: Authorization Request\n with Code Challenge
Keycloak -> User: Login page/Authorization Prompt
User -> Keycloak: Authenticated User with Credentials
Keycloak -> Keycloak: Validate Credentials
Keycloak --> Client: Authorization Code
Client -> Keycloak: Authorization Code\nand Code Verifier
Keycloak -> Keycloak: Validate Code Verifier and\nCode Challenge
Keycloak -> Client: ID Token and Access Token
Client -> ResourceServer: Request Resource with Access Token
Client --> User: Show Resource Data

@enduml
