@startuml normal flow

title Spring Security Filter chain flow

participant "Client Application" as angular
box Resource Server
participant "Springboot Application" as spring
participant "Security Filter Chain" as chain
end box
participant "Keycloak Server" as keycloak

autonumber
angular -> spring: Request resource
spring -> chain: Request resource
chain -> keycloak: Validate token
keycloak -> keycloak: Token validation
keycloak -> chain: Token validation result
alt Token is valid
chain -> chain: Role claim from JWT Token
chain -> chain: Match role claim with \nrequest resource permission
alt Role claim matches with \nrequest resource permission
chain -> spring: Allow route access
spring -> angular: Response resource
else Role claim does not match with \nrequest resource permission
chain -> spring: Deny route access
spring -> angular: Response 403 resource
end
else Token is invalid
chain -> spring: Deny route access
spring -> angular: Response 401 resource
end
@enduml