@startuml normal flow

title Idle timeout mechanism

actor User as User
box "Client application"
participant "Client application" as app
participant "Timer" as timer


autonumber
User -> app: User interacts with application
app -> timer: Start timer
alt user is active
User -> app: Interact with application
app -> timer: Reset timer
else User is idle
timer -> app: Timeout
end box
app -> Keycloak: Logout request
Keycloak -> Keycloak: Logout user
Keycloak -> app: Logout response
app -> User: Redirect to login page

end

@enduml