@startuml normal flow

title Token validation Flow

participant "Resource Server" as Server
participant "Keycloak Server" as Keycloak

autonumber
Server -> Keycloak: Sent introspect request with token\n and client credentials
Keycloak -> Keycloak: Introspect token
Keycloak -> Server: Introspect result

@enduml